<?php

/**
 * This file is to create SQL views based on the existing SQL tables. These
 * will be in the ActiveRecord format.
 * 
 * For this we need to;
 * 1. Add created_at and updated_at columns to tables as appropriate
 * 2. Add lock version where appropriate?
 * 3. Add deleted_at for soft deletes if appropriate
 * 4. Create VIEWs for each table which will be prefixed "x_" so they can have
 *      the same names as existing tables when required
 * 5. Use snake_case for column names
 * 6. Use pluralised snake_case for table names
 * 7. "id" for primary key, singlular "order_id" foreign key format
 * 
 * This should be one of the last every .php migration files in this project.
 * The aim after this is to move to Laravel's tools for migrations and seeding
 * etc.
 */

throw new Exception("WIP: Exception to prevent execution");

/**
 * Add created_at and updated_at columns
 */

$db->query("ALTER TABLE `auditLogging` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `checkoutItems` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `checkoutSessions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `clubMembershipClasses` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `coaches` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `completedForms` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `emergencyContacts` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `extras` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `extrasRelations` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `galaData` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `galaEntries` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `galas` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `galaSessions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `galaSessionsCanEnter` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `individualFeeTrack` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `listSenders` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `meetResults` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `meets` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `meetsWithResults` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `memberMedical` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `memberPhotography` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `members` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `membershipBatch` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `membershipBatchItems` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `memberships` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `membershipYear` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `membershipYearMembers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `newUsers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `notify` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `notifyAdditionalEmails` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `notifyCategories` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `notifyHistory` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `notifyOptions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `onboardingMembers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `onboardingSessions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `passwordTokens` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentCategories` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentMandates` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentMonths` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentPreferredMandate` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentRetries` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `payments` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentSchedule` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentsPayouts` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentsPending` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentSquadFees` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentTypes` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `paymentWebhookOps` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `permissions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `posts` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `qualifications` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `qualificationsMembers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsAttendance` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsBookable` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsBookings` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsSquads` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsVenues` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `sessionsWeek` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `squadMembers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `squadMoves` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `squadReps` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `squads` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripeCustomers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripeDisputes` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripeMandates` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripePaymentItems` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripePayments` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripePayMethods` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `stripePayouts` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `superUsers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `superUsersLogins` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `swimEnglandCompliance` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `targetedListMembers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `targetedLists` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `teamManagers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `tenantOptions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `tenantPaymentIntents` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `tenantRedirect` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `tenants` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `tenantStripeCustomers` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `timesIndividual` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `trainingLogs` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `userLogins` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `userOptions` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `users` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");

$db->query("ALTER TABLE `auditLogging` ADD `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;");