/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "cashier.payment": [
        {
            "name": "id"
        }
    ],
    "cashier.webhook": [],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag"
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag"
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id"
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.index": [
        {
            "name": "view"
        }
    ],
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.tokens.index": [],
    "passport.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "passport.clients.index": [],
    "passport.clients.store": [],
    "passport.clients.update": [
        {
            "name": "client_id"
        }
    ],
    "passport.clients.destroy": [
        {
            "name": "client_id"
        }
    ],
    "passport.scopes.index": [],
    "passport.personal.tokens.index": [],
    "passport.personal.tokens.store": [],
    "passport.personal.tokens.destroy": [
        {
            "name": "token_id"
        }
    ],
    "sanctum.csrf-cookie": [],
    "telescope": [
        {
            "name": "view"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "stancl.tenancy.asset": [
        {
            "name": "path"
        }
    ],
    "central.home": [],
    "central.report_an_error": [],
    "central.clubs": [],
    "central.clubs.redirect": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.admin.index": [],
    "central.my_account.index": [],
    "central.my_account.profile": [],
    "central.my_account.": [],
    "central.my_account.security": [],
    "central.my_account.webauthn_verify": [],
    "central.my_account.webauthn_challenge": [],
    "central.my_account.webauthn_delete": [
        {
            "name": "credential",
            "binding": "id"
        }
    ],
    "central.tenant_users.index": [],
    "central.users.show": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "central.notify": [],
    "central.notify.download_file": [
        {
            "name": "email",
            "binding": "ID"
        }
    ],
    "central.notify-sms": [],
    "central.invoices.show": [
        {
            "name": "invoiceId"
        }
    ],
    "central.tenants": [],
    "central.tenants.show": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.": [],
    "central.tenants.administrators": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.administrators.delete": [
        {
            "name": "tenant",
            "binding": "ID"
        },
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "central.tenants.stripe": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.apple_pay_domains": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.delete_apple_pay_domains": [
        {
            "name": "tenant",
            "binding": "ID"
        },
        {
            "name": "id"
        }
    ],
    "central.tenants.billing": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.billing.add_payment_method": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.billing.add_payment_method_success": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.billing.update_payment_method": [
        {
            "name": "tenant",
            "binding": "ID"
        },
        {
            "name": "id"
        }
    ],
    "central.tenants.billing.delete_payment_method": [
        {
            "name": "tenant",
            "binding": "ID"
        },
        {
            "name": "id"
        }
    ],
    "central.invoices.download": [
        {
            "name": "tenant",
            "binding": "ID"
        },
        {
            "name": "invoice"
        }
    ],
    "central.tenants.billing.portal": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.setup_stripe": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.setup_stripe_redirect": [],
    "central.tenants.pay_as_you_go": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.top_up": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.tenants.top_up_success": [
        {
            "name": "tenant",
            "binding": "ID"
        }
    ],
    "central.aad.start": [],
    "central.aad.verify": [],
    "central.register": [],
    "central.login": [],
    "central.two_factor": [],
    "central.two_factor.resend": [],
    "central.password.request": [],
    "central.password.email": [],
    "central.password.reset": [
        {
            "name": "token"
        }
    ],
    "central.password.update": [],
    "central.webauthn.verify": [],
    "central.webauthn.challenge": [],
    "central.verification.notice": [],
    "central.verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "central.verification.send": [],
    "central.password.confirm": [],
    "central.confirm-password.oauth": [],
    "central.confirm-password.oauth-verify": [],
    "central.confirm-password.webauthn.verify": [],
    "central.confirm-password.webauthn.challenge": [],
    "central.logout": [],
    "index": [],
    "about_changes": [],
    "report_an_error": [],
    "register": [],
    "login": [],
    "login.oauth": [],
    "login.oauth_verify": [],
    "login.signed_email": [],
    "login.check_user": [],
    "two_factor": [],
    "two_factor.resend": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.update": [],
    "webauthn.verify": [],
    "webauthn.challenge": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "confirm-password.oauth": [],
    "confirm-password.oauth-verify": [],
    "confirm-password.webauthn.verify": [],
    "confirm-password.webauthn.challenge": [],
    "logout": [],
    "verification.verify_change": [
        {
            "name": "user"
        },
        {
            "name": "email"
        }
    ],
    "login.v1": [],
    "my_account.index": [],
    "my_account.profile": [],
    "my_account.": [],
    "my_account.email": [],
    "my_account.additional_email": [],
    "my_account.security": [],
    "my_account.create_totp": [],
    "my_account.save_totp": [],
    "my_account.delete_totp": [],
    "my_account.webauthn_verify": [],
    "my_account.webauthn_challenge": [],
    "my_account.webauthn_delete": [
        {
            "name": "credential",
            "binding": "id"
        }
    ],
    "members.index": [],
    "members.combobox": [],
    "members.squads": [
        {
            "name": "member",
            "binding": "MemberID"
        }
    ],
    "members.show": [
        {
            "name": "member",
            "binding": "MemberID"
        }
    ],
    "members.": [
        {
            "name": "path"
        }
    ],
    "squads.": [
        {
            "name": "path"
        }
    ],
    "squads.index": [],
    "squads.combobox": [],
    "squads.new": [],
    "squads.show": [
        {
            "name": "squad",
            "binding": "SquadID"
        }
    ],
    "squads.add-coach": [
        {
            "name": "squad",
            "binding": "SquadID"
        }
    ],
    "squads.delete-coach": [
        {
            "name": "squad",
            "binding": "SquadID"
        },
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "squads.edit": [
        {
            "name": "squad",
            "binding": "SquadID"
        }
    ],
    "squads.delete": [
        {
            "name": "squad",
            "binding": "SquadID"
        }
    ],
    "squad-moves.index": [],
    "squad-moves.create": [],
    "squad-moves.update": [
        {
            "name": "squadMove",
            "binding": "ID"
        }
    ],
    "squad-moves.delete": [
        {
            "name": "squadMove",
            "binding": "ID"
        }
    ],
    "users.index": [],
    "users.combobox": [],
    "users.show": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.statements.index": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.statements.show": [
        {
            "name": "user",
            "binding": "UserID"
        },
        {
            "name": "statement",
            "binding": "id"
        }
    ],
    "users.transactions.index": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.payments.index": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.payment_methods.index": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.payments.show": [
        {
            "name": "user",
            "binding": "UserID"
        },
        {
            "name": "payment",
            "binding": "id"
        }
    ],
    "users.top_up.index": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.top_up.new": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.top_up.create": [
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "users.top_up.show": [
        {
            "name": "user",
            "binding": "UserID"
        },
        {
            "name": "top_up"
        }
    ],
    "users.": [
        {
            "name": "path"
        }
    ],
    "notify.email.history": [],
    "notify.email.download_file": [
        {
            "name": "email",
            "binding": "ID"
        }
    ],
    "notify.sms.new": [],
    "notify.": [],
    "notify.sms.history": [],
    "payments.index": [],
    "payments.methods.index": [],
    "payments.methods.new": [],
    "payments.methods.new_direct_debit": [],
    "payments.methods.new_success": [],
    "payments.methods.delete": [
        {
            "name": "paymentMethod",
            "binding": "id"
        }
    ],
    "payments.methods.update": [
        {
            "name": "paymentMethod",
            "binding": "id"
        }
    ],
    "payments.ledgers.journals.combobox": [],
    "payments.ledgers.index": [],
    "payments.ledgers.new": [],
    "payments.ledgers.": [
        {
            "name": "ledger",
            "binding": "id"
        }
    ],
    "payments.ledgers.show": [
        {
            "name": "ledger",
            "binding": "id"
        }
    ],
    "payments.ledgers.journals.new": [
        {
            "name": "ledger",
            "binding": "id"
        }
    ],
    "payments.ledgers.journals.show": [
        {
            "name": "ledger",
            "binding": "id"
        },
        {
            "name": "journal",
            "binding": "id"
        }
    ],
    "payments.statements.index": [],
    "payments.statements.show": [
        {
            "name": "statement",
            "binding": "id"
        }
    ],
    "payments.entries.new": [],
    "payments.entries.post": [
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "payments.entries.view": [
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "payments.entries.amend": [
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "payments.entries.add_user": [
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "payments.entries.delete_user": [
        {
            "name": "entry",
            "binding": "id"
        },
        {
            "name": "user",
            "binding": "UserID"
        }
    ],
    "payments.entries.add_line": [
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "payments.entries.delete_line": [
        {
            "name": "entry",
            "binding": "id"
        },
        {
            "name": "line",
            "binding": "id"
        }
    ],
    "payments.transactions.index": [],
    "payments.payments.index": [],
    "payments.payments.show": [
        {
            "name": "payment",
            "binding": "id"
        }
    ],
    "payments.payments.refund": [
        {
            "name": "payment",
            "binding": "id"
        }
    ],
    "payments.checkout.show": [
        {
            "name": "payment",
            "binding": "id"
        }
    ],
    "payments.checkout.success": [
        {
            "name": "payment",
            "binding": "id"
        }
    ],
    "payments.checkout.create": [],
    "payments.top_ups.index": [],
    "payments.top_ups.show": [
        {
            "name": "top_up"
        }
    ],
    "payments.": [],
    "renewals.index": [],
    "renewals.new": [],
    "renewals.create": [],
    "renewals.show": [
        {
            "name": "renewal",
            "binding": "id"
        }
    ],
    "renewals.edit": [
        {
            "name": "renewal",
            "binding": "id"
        }
    ],
    "renewals.update": [
        {
            "name": "renewal",
            "binding": "id"
        }
    ],
    "venues.index": [],
    "venues.new": [],
    "venues.": [],
    "venues.show": [
        {
            "name": "venue",
            "binding": "id"
        }
    ],
    "venues.combobox": [],
    "competitions.index": [],
    "competitions.new": [],
    "competitions.": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "header",
            "binding": "id"
        },
        {
            "name": "entrant",
            "binding": "id"
        }
    ],
    "competitions.show": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.edit": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.guest_entries.index": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.guest_entries.report": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.guest_entries.show": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "entry",
            "binding": "id"
        }
    ],
    "competitions.sessions.index": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.sessions.": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "session",
            "binding": "id"
        }
    ],
    "competitions.sessions.show": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "session",
            "binding": "id"
        }
    ],
    "competitions.sessions.edit": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "session",
            "binding": "id"
        }
    ],
    "competitions.sessions.events.create": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "session",
            "binding": "id"
        }
    ],
    "competitions.sessions.events.delete": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "session",
            "binding": "id"
        },
        {
            "name": "event",
            "binding": "id"
        }
    ],
    "competitions.enter_as_guest": [
        {
            "name": "competition",
            "binding": "id"
        }
    ],
    "competitions.enter_as_guest.show": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "header",
            "binding": "id"
        }
    ],
    "competitions.enter_as_guest.pay": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "header",
            "binding": "id"
        }
    ],
    "competitions.enter_as_guest.express_pay": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "header",
            "binding": "id"
        }
    ],
    "competitions.enter_as_guest.edit_entry": [
        {
            "name": "competition",
            "binding": "id"
        },
        {
            "name": "header",
            "binding": "id"
        },
        {
            "name": "entrant",
            "binding": "id"
        }
    ],
    "settings.index": [],
    "settings.payments": [],
    "settings.": [],
    "notify_additional_emails.view": [
        {
            "name": "data"
        }
    ],
    "notify_additional_emails.confirm": [],
    "notify_additional_emails.delete": [
        {
            "name": "additionalEmail",
            "binding": "ID"
        }
    ]
}
}
export {};
