name: Build V1 Front End

on:
  push:
    branches: [ "main", "development-main" ]
  pull_request:
    branches: [ "main", "development-main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      working-directory: ./src_v1
      run: |
        npm install
        npm run build
